server: 
    #将tomcat默认端口 8080 设置成 8085
    port: 8085 
    #将默认访问路径从“/”改为“/star”
    servlet:
      context-path: /star

#logging: 
 # config: classpath:logback-boot.xml

# 自定义静态资源目录
#spring: 
#  resources: 
#    static-locations: classpath:/statics11 

# 自动以静态资源访问路径
#spring: 
#  mvc: 
#    static-path-pattern: /image/**


spring: 
  # 数据库配置
  datasource: 
    url: jdbc:mysql://localhost:3306/yiibaidb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123=123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
# mybatis配置    
mybatis: 
  # 配置映射类所在包名
  type-aliases-package: com.example.srpingBoot.order
  mapper-locations: classpath:mapper/*.xml

